# Generated by Django 2.2.12 on 2020-11-15 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('job_title', models.CharField(max_length=100)),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female')])),
            ],
        ),
    ]
