# Generated by Django 2.2.12 on 2020-11-18 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=20)),
                ('activity_time', models.DateTimeField()),
                ('activity_request', models.TextField()),
                ('activity_response', models.TextField()),
                ('user', models.IntegerField()),
            ],
        ),
    ]
